# defining the list of x15 questions 
questions = [
    ("What colors is the flag of the United Nations?",
     "Blue and Red",
     "Purple and Blue",
     "Blue and White",
     "Green and Blue",
     3),
    ("What is the capital of Canada?",
     "Ottawa",
     "Toronto",
     "Vancouver",
     "Montreal",
     1),
    ("What country uses the Yen (¥) currency?",
     "China",
     "Japan",
     "Vietnam",
     "Russia",
     2),
    ("What is the name of the tallest mountain in the world?",
     "Mount Cook, New Zealand",
     "Mount Fuji, Japan",
     "Mount Everest, China",
     "Mount Kanchenjunga, India",
     3),
    ("Which country has the largest population in the world?",
     "Russia",
     "China",
     "India",
     "United States of America",
     2),
    ("What city in the USA is the Golden Gate Bridge located in?",
     "Orlando, Florida",
     "San Francisco, California",
     "Dallas, Texas",
     "Los Angeles, California",
     2),
    ("What is the largest country in the world?",
     "China",
     "United States of America",
     "Canada",
     "Russia",
     4),
    ("Where is the Eiffel Tower located?",
     "Italy",
     "Paris",
     "Finland",
     "Switzerland",
     2),
    ("What is the largest ocean in the world?",
     "Indian Ocean",
     "Pacific Ocean",
     "Atlantic Ocean",
     "Arctic Ocean",
     2),
    ("Mount Fuji is the highest point located in which Asian country?",
     "China",
     "Japan",
     "South Korea",
     "Thailand",
     2),
    ("What is the highest mountain in New Zealand?",
     "Mount Ruapehu, Waikato",
     "‘Aoraki’ Mount Cook, Canterbury",
     "Mount Taranaki, Taranaki",
     "‘Tititea’ Mount Aspiring, Otago",
     2),
    ("In which country is the Leaning Tower of Pisa located?",
     "France",
     "Italy",
     "Greece",
     "Finland",
     2),
    ("“The Lord of The Rings” film was produced in what country?",
     "New Zealand",
     "USA",
     "Australia",
     "Canada",
     1),
    ("Peking Duck is the national dish of what country?",
     "Russia",
     "China",
     "Italy",
     "Japan",
     2),
    ("What season does Australia experience in December?",
     "Summer",
     "Winter",
     "Autumn",
     "Spring",
     1)
]
